# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a64401c0e61f6ecaaaa49ce929d09fd4c636567e4c15dfefccb2ae24ee19d1fefbf115e7c24bb8ebb7b875d597620725417087204c597029a5c823fc6951e35

test:
  secret_key_base: ec346fc9cd0d69525763570ebcc0f2a1a564a19122f6b2bac273682e712a8942bf05f04c9c8150c63559fae6287654824b65610d6873ef00b339d5fa6f404184

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
